/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.core.security.authz.support;

import org.elasticsearch.action.ActionListener;
import org.elasticsearch.xpack.core.security.authc.Authentication;
import org.elasticsearch.xpack.core.security.authz.ResolvedIndices;
import org.elasticsearch.xpack.core.security.authz.permission.DocumentPermissions;
import org.elasticsearch.xpack.core.security.authz.permission.DocumentSecurityQuery;
import org.elasticsearch.xpack.core.security.authz.permission.Role;
import org.elasticsearch.xpack.core.security.user.User;

/**
 * Evaluates Document Level Security (see {@link DocumentPermissions#hasDocumentLevelPermissions()} queries for templates or extensions.
 * <br>
 * Document level security queries can be static (a fixed query) or dynamic (evaluated at runtime by a template, or generated by a security
 * extension).
 * Implementations of this interface are responsible for turning a dyanmic DLS query specification into a fixed ES query at runtime.
 */
public interface DlsQueryBuilder {

    DocumentSecurityQuery build(String querySource, User user);

    /**
     * The {@link #build} method is synchronous and it is not safe for any DLS extension to perform asynchronous tasks (actions) during
     * query building. If an extension needs to perform asynchronous tasks then it has to do it here, in advance of query building.
     */
    default void precache(Authentication authentication, Role role, ResolvedIndices requestedIndices, ActionListener<Void> listener) {
        listener.onResponse(null);
    }
}
