/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.core.security.authz.support;

import org.elasticsearch.common.bytes.BytesReference;
import org.elasticsearch.xpack.core.security.authz.permission.DocumentPermissions;
import org.elasticsearch.xpack.core.security.user.User;

import java.util.function.Supplier;

/**
 * Evaluates Document Level Security (see {@link DocumentPermissions#hasDocumentLevelPermissions()} queries for templates or extensions.
 * <br>
 * Document level security queries can be static (a fixed query) or dynamic (evaluated at runtime by a template, or generated by a security
 * extension).
 * Implementations of this interface are responsible for turning a dyanmic DLS query specification into a fixed ES query at runtime.
 */
public interface DlsQueryEvaluator {

    @FunctionalInterface
    interface UserContext {
        String evaluate(BytesReference query);
    }

    /**
     * Parser the provided "query", determines whether it is a dynamic query, and if so evaluates it, then returns the resultant string
     * (which should be in Elasticsearch Query DSL)
     * <br>
     * If the source does not contain a dynamic query, then this method will return the query source without any modifications.
     */
    String evaluate(String querySource, User user);

    default UserContext bind(User user) {
        return query -> evaluate(query.utf8ToString(), user);
    }

    /**
    * <em>Urgh</em> We need this because TransportTermsEnumAction depends on core, but not security
     * But we need the real evaluator to live in security because it depends on security extensions
     * But with another layer of indirection, we can let the TransportTermsEnumAction depend on a provider, and have security
     * update the provider after it's loaded.
     * Yes, it's as bad as it sounds.
      */
    interface LateBinding extends Supplier<DlsQueryEvaluator> {}
}
