/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the Elastic License
 * 2.0; you may not use this file except in compliance with the Elastic License
 * 2.0.
 */

package org.elasticsearch.xpack.core.security.authz.support;

import org.elasticsearch.xpack.core.security.authz.permission.DocumentPermissions;
import org.elasticsearch.xpack.core.security.authz.permission.DocumentSecurityQuery;
import org.elasticsearch.xpack.core.security.user.User;

/**
 * Evaluates Document Level Security (see {@link DocumentPermissions#hasDocumentLevelPermissions()} queries for templates or extensions.
 * <br>
 * Document level security queries can be static (a fixed query) or dynamic (evaluated at runtime by a template, or generated by a security
 * extension).
 * Implementations of this interface are responsible for turning a dyanmic DLS query specification into a fixed ES query at runtime.
 */
public interface DlsQueryBuilder {

    DocumentSecurityQuery build(String querySource, User user);
}
