apply plugin: 'elasticsearch.base-internal-es-plugin'
apply plugin: 'elasticsearch.internal-java-rest-test'

esplugin {
  name = 'test-dls-extension-plugin'
  description = 'A plugin for testing DlsQueryExtension'
  classname = 'org.elasticsearch.xpack.security.authz.dls.extension.DlsExtPlugin'
  extendedPlugins = ['x-pack-core', 'x-pack-security']
}

dependencies {
  compileOnly project(':x-pack:plugin:core')
  compileOnly project(':x-pack:plugin:security')
  clusterPlugins project(':x-pack:plugin:security:qa:dls-extension')

  javaRestTestImplementation project(':x-pack:plugin:core')
  javaRestTestImplementation project(':x-pack:plugin:security')
  javaRestTestImplementation project(':test:framework')
}

tasks.named('javaRestTest') {
  usesDefaultDistribution("Needs security")
}

tasks.named("javadoc").configure { enabled = false }

